.\" Manpage for bat
.\" honeydatax
.TH man 0 "15 APR 2017"1.0"bat man page
.SH NAME
bat \- bat multitask evironent to bash commands
.SH SYNOPSIS
bat [file.in] [file.out] 
.SH DESCRIPTION
bat is utility to multitask evironent to bash commands prints help files in the screen
.SH OPTIONS
bat [file.in] the mkfifo file to get the e\n command or exit command or bat end command ,[file.out] mkfifo file output of command graphics out in the screen ,commands to fifo file n for new windows: n[h] [w] [y] [x] [color 1..3]\n , command: p to print in a windows same text: p[windows number] [y] [x] [text to print]\n, command s to sleep to suspend the run for n seconds: s[seconds]\n,command e exit get out of bat utulity : e\n
.SH ALSO
more honey datax on net
.SH BUGS
not complet yet
.SH AUTHOR
honeydatax













