.\" Manpage for sub
.\" honeydatax
.TH man 0 "15 APR 2017"1.0"sub man page
.SH NAME
sub \- sub two integer numbers and save it to file
.SH SYNOPSIS
sub [number] [number] [file.txt]
.SH DESCRIPTION
sub is a program to sub two numbers and to output the solved resolt into  a file to be used in command line
.SH OPTIONS
2 integer number to subtract to and file name to put the solve resolt
.SH ALSO
more honey datax on net
.SH BUGS
not complet yet
.SH AUTHOR
honeydatax













